#Country capitals original dictionary list
COUNTRY_CAPITALS = {'United States': 'Washington D.C.',
                    'Canada': 'Ottawa',
                    'United Kingdom': 'London',
                    'Russia': 'Moscow',
                    'South Korea': 'Seoul',
                    'France': 'Paris',
                    'Greece': 'Athens',
                    'New Zealand': 'Wellington',
                    'Brazil': 'Brasillia',
                    'Colombia': 'Bogota',
                    'China': 'Bejing',
                    'Costa Rica': 'San Jose',
                    'Spain': 'Madrid',
                    'Thailand': 'Bangkok',
                    'Poland': 'Warsaw',
                    'Ireland': 'Dublin',
                    'Italy': 'Rome',
                    'Israel': 'Jerusalem',
                    'Iraq': 'Baghdad',
                    'Haiti': 'Port au Prince',}
#Country capitals reload dictionary list
def reload_country_capitals(capitals):
    capitals = {'United States': 'Washington D.C.',
                    'Canada': 'Ottawa',
                    'United Kingdom': 'London',
                    'Russia': 'Moscow',
                    'South Korea': 'Seoul',
                    'France': 'Paris',
                    'Greece': 'Athens',
                    'New Zealand': 'Wellington',
                    'Brazil': 'Brasillia',
                    'Colombia': 'Bogota',
                    'China': 'Bejing',
                    'Costa Rica': 'San Jose',
                    'Spain': 'Madrid',
                    'Thailand': 'Bangkok',
                    'Poland': 'Warsaw',
                    'Ireland': 'Dublin',
                    'Italy': 'Rome',
                    'Israel': 'Jerusalem',
                    'Iraq': 'Baghdad',
                    'Haiti': 'Port au Prince',}


